# Generated by Django 4.2.5 on 2023-12-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podcast_images/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
