# Generated by Django 4.2.5 on 2023-12-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_caterogies_podcast_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='authors',
            new_name='author',
        ),
    ]
